### ISSUE TITLE
Shaping issues for letters at the end of a line. + Coloring issues.

### ISSUE THREAD

**Issue by asibahi** [aliftype/raqq#26] opened 2024-04-06 20:04 UTC
Hello.

First, thanks for the font. Your work is an inspiration.

I have been playing with the font in my Arabic justification experiments ([which can be found here](https://github.com/asibahi/noor)) , and I noticed some odd behaviors for shaping when it is the last letter in a line. I do not know if this is an issue with the font or if it is an issue somewhere in my code.

The image in the repo has an example of what I am talking about in the ي at the end of دري . 

<img width="544" alt="image" src="https://github.com/aliftype/raqq/assets/17417266/12236d53-6b63-468d-ac1e-efeae5209621">

You will see that the Yea's dots are .. shifted a bit

Here is another example with a different word : على 

<img width="544" alt="image" src="https://github.com/aliftype/raqq/assets/17417266/e29248bc-22ec-4909-8a33-d5bd2163710b">

I also notice it when a word ending with ل like كل or مثل at the end of a line. I am using the latest release of Raqq. I am not sure what version of Harfbuzz I am using. (Everything related to C libraries is entirely confusing to me).

---

Regarding coloring : Again I have no knowledge if this is a font issue or a tech stack issue:

When drawing the glyphs with a different color than white I encounter odd artifacts on some letters like seen in this image.

![noor_49](https://github.com/aliftype/raqq/assets/17417266/b579f09b-b7a9-4f73-8b2a-385b80f237c2)

I managed to work around by actually drawing the letters as transparent and just overlaying that over another image with text's color, so it is not an issue. But thought it was worth pointing out.

Thanks again.

**Comment by khaledhosny** [comment] 2024-04-08 18:37
> I noticed some odd behaviors for shaping when it is the last letter in a line.

Fonts know nothing about line end, so I don’t think there is a font issue here. Using `hb-view`, the word looks fine:
![](https://github.com/aliftype/raqq/assets/93914/997b0e20-0a7f-45e6-99c2-454db7a9133c)

> When drawing the glyphs with a different color than white I encounter odd artifacts on some letters like seen in this image.

This might be caused by differences in path direction between glyphs. Can you try the latest commit?

**Comment by khaledhosny** [comment] 2024-04-08 18:38
Cool project, BTW, the justification looks really nice. I should give it a try.

**Comment by asibahi** [comment] 2024-04-08 20:00
Thanks for the kind words. Much appreciated. 

This is with the latest commit font. Same issue with colors.

![noor_52](https://github.com/aliftype/raqq/assets/17417266/c0cee5bd-ae9f-4ea3-adb2-c5ef3d6f8792)

regarding the shaping issue, I noticed that it occurs when I pass to HarfBuzz a trimmed string. The code sample below: the commented out line is where it affects it. I ended up trimming only the last line (because it renders a tofu if I dont?) but shifting all the other lines by the last space's `x_advance`.

```rust
    let hb_buffer = hb::UnicodeBuffer::new().add_str_item(TEXT, &TEXT[start_bp..end_bp]);
    // let hb_buffer = hb::UnicodeBuffer::new().add_str_item(TEXT, TEXT[start_bp..end_bp].trim());
    let hb_output = hb::shape(&hb_font, hb_buffer, &[]);```

You will notice in the image above how the ي in دري is shifted slightly leftwards.

**Comment by khaledhosny** [comment] 2024-04-09 15:15
> This is with the latest commit font. Same issue with colors.

How do I reproduce this using your repo? I tried this change:
```diff
diff --git a/src/main.rs b/src/main.rs
index cecda22..4c22533 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -32,8 +32,8 @@ const _OFF_BLACK: [u8; 4] = [0x20, 0x20, 0x20, 0xFF];
 const _GOLD_ORNG: [u8; 4] = [0xB4, 0x89, 0x39, 0xFF];
 const _NAVY_BLUE: [u8; 4] = [0x13, 0x2A, 0x4A, 0xFF];

-const TXT_COLOR: image::Rgba<u8> = image::Rgba(_BLACK);
-const BKG_COLOR: image::Rgba<u8> = image::Rgba(_OFF_WHITE);
+const TXT_COLOR: image::Rgba<u8> = image::Rgba(_GOLD_ORNG);
+const BKG_COLOR: image::Rgba<u8> = image::Rgba(_NAVY_BLUE);

 fn main() -> Result<(), Box<dyn std::error::Error>> {
     let font_data = std::fs::read("fonts/Raqq.ttf")?;
```

But I don’t get any color artifacts:
![noor_50](https://github.com/aliftype/raqq/assets/93914/3350a6a8-806d-4ac7-94bf-03ebdae3e365)

> regarding the shaping issue, I noticed that it occurs when I pass to HarfBuzz a trimmed string. The code sample below: the commented out line is where it affects it. I ended up trimming only the last line (because it renders a tofu if I dont?) but shifting all the other lines by the last space's `x_advance`.

I don’t know much about Rust to get what this code is doing.

**Comment by khaledhosny** [comment] 2024-04-09 17:33
> This branch reproduces the issue: https://github.com/asibahi/noor/tree/reproduce_color_artifacts
> 
> The difference between this one and master is that _master_ draws the letters as transparent (`[0, 0, 0, 0]`) and overlays it over the text color.

I fixed the issue with س (which was a genuine bug), the other artifacts look like a bug in the rendering library/rasterizer not being able to handle overlapping paths.

**Comment by khaledhosny** [comment] 2024-04-25 12:20
> This branch reproduces the shaping artifacts: https://github.com/asibahi/noor/tree/reproduce_shaping_artifact .

Like I said, I don’t know much rust, but it seems like a bug in ab_glyph. It looks like if a zero-width glyph is constructed at x=0 position, the min x of the next glyph bounds are wrong.

This patch that avoids x ever being zero by initializing it to the margin value, seems to workaround this issue:
```diff
diff --git a/src/main.rs b/src/main.rs
index 7bd41c6..1bae0a6 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -131,7 +131,7 @@ fn write_in_image(

     let ascent = ab_scaled_font.ascent();

-    let mut caret = 0;
+    let mut caret = MARGIN as f32;

     let mut colored_glyphs = vec![];

@@ -143,12 +143,12 @@ fn write_in_image(
         let gl = ab::GlyphId(info.codepoint as u16).with_scale_and_position(
             ab_scale,
             ab::point(
-                (caret + position.x_offset) as f32 * scale_factor.horizontal,
+                caret + (position.x_offset as f32 * scale_factor.horizontal),
                 ascent - (position.y_offset as f32 * scale_factor.vertical),
             ),
         );

-        caret += position.x_advance;
+        caret += position.x_advance as f32 * scale_factor.horizontal;

         let Some(outlined_glyph) = ab_font.outline_glyph(gl) else {
             // gl is whitespace
@@ -156,7 +156,7 @@ fn write_in_image(
         };

         let bb = outlined_glyph.px_bounds();
-        let bbx = bb.min.x as u32 + MARGIN;
+        let bbx = bb.min.x as u32;
         let bby = bb.min.y as u32 + MARGIN + line as u32 * LINE_HEIGHT;

         if let Some(colored_glyph) = ab_font
```

**Comment by khaledhosny** [comment] 2024-04-25 12:20
Closing this as it is neither a font nor a shaping issue.

**Closed by khaledhosny** 2024-04-25 12:20 UTC
